CREATE TABLE `bike` (
  `id` int(11) NOT NULL,
  `brand` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `spec` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `category` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `color` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `frame_sizes` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `frame` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `fork` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `derailleur_front` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `derailleur_rear` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `shifters` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `break_lever` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `brakes` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `pic_bike_1` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `pic_bike_2` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `pic_bike_3` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `pic_bike_4` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `gender` varchar(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `body_height` int(11) NOT NULL,
  `body_weight` int(11) NOT NULL,
  `min_torso_length` int(11) NOT NULL,
  `max_torso_length` int(11) NOT NULL,
  `min_arm_length` int(11) NOT NULL,
  `max_arm_length` int(11) NOT NULL,
  `min_shoulder_length` int(11) NOT NULL,
  `max_shoulder_length` int(11) NOT NULL,
  `price` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;